### ISSUE TITLE
no commands work - command not found

### ISSUE THREAD

**Issue by momsi** [cpwood/Pico-Go#118]
## What are the steps to reproduce this issue?
1. Install Pico-Go extension
2. Try executing any command (e.g. global settings)

## What happens?
Error message: 
Command 'Pico-Go > Global Settings' resulted in an error (command 'picogo.globalSettings' not found)

## What were you expecting to happen?
correctly execute command

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*
only the error message

## Any other comments?
this happens with every command. 

Can now add info that Pymakr also has the same issue. When installing Pymakr is throws an error "There was an error with your serialport module".

## Support info

Copy this from the `Pico-Go > Help > Get support info` option in the command palette:
 ** Unable ... shows the same error message **

**Comment by arnytrty** [comment]
Hey, just letting you know there is already an issue #113

**Comment by SEIDO-JP** [comment]
Yes, I can confirm. The problem occurs on both MacOS and Windows.

I spent a few hours yesterday trying to run Pico-Go on VSCode for the first time ... : /

**Comment by SEIDO-JP** [comment]
Yes, I can confirm. The problem occurs on both MacOS and Windows.

I spent a few hours yesterday trying to run Pico-Go on VSCode for the first time ... : /

**Comment by BEMBELmotorsport** [comment]
I have the same Problem on Windows 10. Pico-Go was running fine until VS Code version changed to 1.66.0 two days ago.
I tried a different (older) version of Pico-Go and even uninstalled and reinstalled Pico-Go but the problem is still there.

**Comment by arnytrty** [comment]
As **temporary** solution you can downgrade to VSCode/VSCodium **1.65.2**

Also the reason of this issue is described in VSCode [changelog](https://code.visualstudio.com/updates/v1_66#_nodemoduleversion-and-nodejs-api-update):

For extension authors using native node modules, this release bumps the Node.js version from `14.16.0` to `16.13.0`, which might have an impact on your module compilation depending on which API abstraction layer is used.

**Comment by momsi** [comment]
Can confirm this workes! Thanks a lot.

> As **temporary** solution you can downgrade to VSCode/VSCodium **1.65.2**
> 
> Also the reason of this issue is described in VSCode [changelog](https://code.visualstudio.com/updates/v1_66#_nodemoduleversion-and-nodejs-api-update):
> 
> For extension authors using native node modules, this release bumps the Node.js version from `14.16.0` to `16.13.0`, which might have an impact on your module compilation depending on which API abstraction layer is used.

**Comment by SEIDO-JP** [comment]
Hi @momsi,

I don't know if this is a good idea to close this issue. Downgrading VSCode is only a temporary solution and still Pico-Go should be fixed to work with up to date VSCode version.

**Comment by momsi** [comment]
> Hi @momsi,
> 
> I don't know if this is a good idea to close this issue. Downgrading VSCode is only a temporary solution and still Pico-Go should be fixed to work with up to date VSCode version.

You're right .... reopened

**Comment by RoulstoneR** [comment]
Thank you, everyone. I have been pulling out what's left of my hair. Downgrading VSCODE worked a treat.

**Comment by RCPhysics** [comment]
Can confirm that on MacOS 12.3.1 M1 Max this is an issue still.  Downgrading VS Code as described above "fixes" the issue.

**Comment by slowpokefarm** [comment]
Have the same issue on Ubuntu.
VSCode: 1.66.1
Node.js: 16.13.0
OS: Linux x64 5.4.0-107-generic

How do you downgrade vscode? Ubuntu won't let me install the lower version.

**Comment by MarkoBogSrb** [comment]
Same issue - will try the downgrading of VScode

**Comment by jasongi** [comment]
See temporary fix here:
https://github.com/cpwood/Pico-Go/issues/123#issuecomment-1158870243
